/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clientgui;

/**
 *
 * @author maher
 */
public class clientGUI extends javax.swing.JFrame implements userinterface.userInterface{

    /**
     * Creates new form clientWindow
     */
    public clientGUI() {
        initComponents();
    }
    
    usercommandhandler.userCommandHandler myUserCommandHandler;
            
    public void setUserCommandHandler(usercommandhandler.userCommandHandler myUserCommandHandler) { 
        this.myUserCommandHandler = myUserCommandHandler;
    }
    
    public void update(String theResult) { 
        messagesTextArea.append(theResult + "\n"); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getTimeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagesTextArea = new javax.swing.JTextArea();
        displayServerMessageText = new javax.swing.JLabel();
        setLEDstext = new javax.swing.JLabel();
        getPBstatetext = new javax.swing.JLabel();
        displayPB1state = new javax.swing.JTextField();
        displayPB2state = new javax.swing.JTextField();
        displayPB3state = new javax.swing.JTextField();
        LED1label = new javax.swing.JLabel();
        LED2label = new javax.swing.JLabel();
        LED3label = new javax.swing.JLabel();
        LED4label = new javax.swing.JLabel();
        getPB2state = new javax.swing.JButton();
        getPB3state = new javax.swing.JButton();
        setLED1 = new javax.swing.JCheckBox();
        setLED2 = new javax.swing.JCheckBox();
        setLED3 = new javax.swing.JCheckBox();
        setLED4 = new javax.swing.JCheckBox();
        ConnectServer = new javax.swing.JButton();
        DisconnectServer = new javax.swing.JButton();
        getPB1tsate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        getTimeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getTimeButton.setText("GetTime");
        getTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTimeButtonActionPerformed(evt);
            }
        });

        messagesTextArea.setColumns(20);
        messagesTextArea.setRows(5);
        jScrollPane1.setViewportView(messagesTextArea);

        displayServerMessageText.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        displayServerMessageText.setText("Server Messages");
        displayServerMessageText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        setLEDstext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        setLEDstext.setText("Set LEDs");

        getPBstatetext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getPBstatetext.setText("Get PBs State");

        LED1label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LED1label.setText("LED1");

        LED2label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LED2label.setText("LED2");

        LED3label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LED3label.setText("LED4");

        LED4label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LED4label.setText("LED3");

        getPB2state.setText("PB2");
        getPB2state.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getPB2state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPB2stateActionPerformed(evt);
            }
        });

        getPB3state.setText("PB3");
        getPB3state.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getPB3state.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getPB3state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPB3stateActionPerformed(evt);
            }
        });

        setLED1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLED1ActionPerformed(evt);
            }
        });

        setLED2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLED2ActionPerformed(evt);
            }
        });

        setLED3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLED3ActionPerformed(evt);
            }
        });

        setLED4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLED4ActionPerformed(evt);
            }
        });

        ConnectServer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ConnectServer.setText("Connect");
        ConnectServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectServerActionPerformed(evt);
            }
        });

        DisconnectServer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DisconnectServer.setText("DisConnect");
        DisconnectServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisconnectServerActionPerformed(evt);
            }
        });

        getPB1tsate.setText("PB1");
        getPB1tsate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPB1tsateActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("GetTemp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ConnectServer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisconnectServer, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(getTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LED1label)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(setLED1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LED2label)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(setLED2)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(getPB2state, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(displayPB2state, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(getPB1tsate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(displayPB1state, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LED3label)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(setLED4))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LED4label)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(setLED3)
                                            .addGap(18, 18, 18)
                                            .addComponent(getPB3state, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(displayPB3state, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(setLEDstext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(getPBstatetext, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(displayServerMessageText, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConnectServer, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(DisconnectServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getTimeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setLEDstext)
                    .addComponent(getPBstatetext)
                    .addComponent(displayServerMessageText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(displayPB1state, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getPB1tsate))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LED2label)
                                            .addComponent(setLED2))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LED4label)
                                            .addComponent(setLED3))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LED3label)
                                            .addComponent(setLED4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(getPB2state)
                                            .addComponent(displayPB2state, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(getPB3state)
                                            .addComponent(displayPB3state, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(LED1label))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(setLED1)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTimeButtonActionPerformed
        // TODO add your handling code here:
            messagesTextArea.append("Getting time from the Server\n");
            myUserCommandHandler.handleUserCommand("4");
    }//GEN-LAST:event_getTimeButtonActionPerformed

    private void getPB2stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPB2stateActionPerformed
        // TODO add your handling code here:
        messagesTextArea.append("PB2 is on \n");
        myUserCommandHandler.handleUserCommand("14");
    }//GEN-LAST:event_getPB2stateActionPerformed

    private void getPB3stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPB3stateActionPerformed
        // TODO add your handling code here:
        messagesTextArea.append("PB3 is on \n");
        myUserCommandHandler.handleUserCommand("15");
    }//GEN-LAST:event_getPB3stateActionPerformed

    private void setLED1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLED1ActionPerformed
        // TODO add your handling code here:
        if(setLED1.isSelected()==true) {
            messagesTextArea.append("LED1 turned on\n");
            myUserCommandHandler.handleUserCommand("5");
        }else{
            messagesTextArea.append("LED1 turned off\n");
            myUserCommandHandler.handleUserCommand("9");
        }
    }//GEN-LAST:event_setLED1ActionPerformed

    private void setLED2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLED2ActionPerformed
        // TODO add your handling code here:
        if(setLED2.isSelected()==true) {
            messagesTextArea.append("LED2 turned on\n");
            myUserCommandHandler.handleUserCommand("6");
        }else{
            messagesTextArea.append("LED2 turned off\n");
            myUserCommandHandler.handleUserCommand("10");
        }
    }//GEN-LAST:event_setLED2ActionPerformed

    private void setLED3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLED3ActionPerformed
        // TODO add your handling code here:
        if(setLED3.isSelected()==true) {
            messagesTextArea.append("LED3 turned on\n");
            myUserCommandHandler.handleUserCommand("7");
        }else{
            messagesTextArea.append("LED3 turned off\n");
            myUserCommandHandler.handleUserCommand("11");
        }
    }//GEN-LAST:event_setLED3ActionPerformed

    private void setLED4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLED4ActionPerformed
        // TODO add your handling code here:
        if(setLED4.isSelected()==true) {
            messagesTextArea.append("LED4 turned on\n");
            myUserCommandHandler.handleUserCommand("8");
        }else{
            messagesTextArea.append("LED4 turned off\n");
            myUserCommandHandler.handleUserCommand("12");
        }
    }//GEN-LAST:event_setLED4ActionPerformed

    private void ConnectServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectServerActionPerformed
        // TODO add your handling code here:
        messagesTextArea.append("Conecting to the Server\n");
        myUserCommandHandler.handleUserCommand("2");
    }//GEN-LAST:event_ConnectServerActionPerformed

    private void DisconnectServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnectServerActionPerformed
        // TODO add your handling code here:
        messagesTextArea.append("Disconecting from the Server\n");
        myUserCommandHandler.handleUserCommand("3");
    }//GEN-LAST:event_DisconnectServerActionPerformed

    private void getPB1tsateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPB1tsateActionPerformed
        // TODO add your handling code here:
        messagesTextArea.append("PB1 is on \n");
        myUserCommandHandler.handleUserCommand("13");
    }//GEN-LAST:event_getPB1tsateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        messagesTextArea.append("Command to get the temperature: \n");
        myUserCommandHandler.handleUserCommand("14");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        final clientgui.clientGUI myUI = new clientgui.clientGUI();
        client.client myClient = new client.client(7777,myUI);
        servermessagehandler.serverMessageHandler myServerMessageHandler = new servermessagehandler.serverMessageHandler(myClient);
        //myClient.setServerMessageHandler(myServerMessageHandler);
        usercommandhandler.userCommandHandler myUserCommandHandler = new usercommandhandler.userCommandHandler(myUI,myClient);
        myUI.setUserCommandHandler(myUserCommandHandler);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                myUI.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnectServer;
    private javax.swing.JButton DisconnectServer;
    private javax.swing.JLabel LED1label;
    private javax.swing.JLabel LED2label;
    private javax.swing.JLabel LED3label;
    private javax.swing.JLabel LED4label;
    private javax.swing.JTextField displayPB1state;
    private javax.swing.JTextField displayPB2state;
    private javax.swing.JTextField displayPB3state;
    private javax.swing.JLabel displayServerMessageText;
    private javax.swing.JButton getPB1tsate;
    private javax.swing.JButton getPB2state;
    private javax.swing.JButton getPB3state;
    private javax.swing.JLabel getPBstatetext;
    private javax.swing.JButton getTimeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messagesTextArea;
    private javax.swing.JCheckBox setLED1;
    private javax.swing.JCheckBox setLED2;
    private javax.swing.JCheckBox setLED3;
    private javax.swing.JCheckBox setLED4;
    private javax.swing.JLabel setLEDstext;
    // End of variables declaration//GEN-END:variables
}
